In [5]:
from config import config
from get_data import get_data, work_day, work_time

In [6]:
test_config = config["test1"]
test_config

[{'name': 'SHFE.rb2401',
  'frequency': '300s',
  'count': 500,
  'update_count': 10,
  'sleep': 4},
 {'name': 'SHFE.rb2401',
  'frequency': '1d',
  'count': 500,
  'update_count': 10,
  'sleep': 4}]

In [7]:
data=get_data(test_config[0]["name"], test_config[0]["frequency"], test_config[0]["count"],config['refresh'])
data

,time,open,high,low,close,volume,date
0,1.700836e+09,3930.0,3934.0,3928.0,3934.0,13172,2023-11-24 22:30:00+08:00
1,1.700836e+09,3933.0,3943.0,3933.0,3938.0,36552,2023-11-24 22:35:00+08:00
2,1.700837e+09,3937.0,3938.0,3933.0,3935.0,13860,2023-11-24 22:40:00+08:00
3,1.700837e+09,3935.0,3936.0,3928.0,3933.0,16779,2023-11-24 22:45:00+08:00
4,1.700837e+09,3932.0,3934.0,3930.0,3934.0,8554,2023-11-24 22:50:00+08:00
...,...,...,...,...,...,...,...
495,1.701826e+09,3876.0,3877.0,3872.0,3876.0,6410,2023-12-06 09:30:00+08:00
496,1.701826e+09,3875.0,3887.0,3875.0,3883.0,19817,2023-12-06 09:35:00+08:00
497,1.701827e+09,3883.0,3888.0,3880.0,3887.0,12664,2023-12-06 09:40:00+08:00
498,1.701827e+09,3887.0,3894.0,3882.0,3893.0,16905,2023-12-06 09:45:00+08:00
499,1.701827e+09,3894.0,3896.0,3887.0,3890.0,12461,2023-12-06 09:50:00+08:00

In [8]:
import datetime
import chinese_calendar

demo_time = datetime.datetime.now()

data_is_holiday = chinese_calendar.is_holiday(demo_time)
data_is_workday = chinese_calendar.is_workday(demo_time)

In [9]:
print('work_day:',work_day(),'work_time',work_time())

at work time...  2023-12-06 09:57:17.791141
work_day: True work_time True

In [10]:
from config import strategy

strategy

{'base_balance': 1000,
 'datapoints': [{'args': [30], 'transformer': 'sma', 'name': 'sma_short'},
  {'args': [90], 'transformer': 'sma', 'name': 'sma_long'}],
 'enter': [['close', '>', 'sma_long'], ['close', '>', 'sma_short']],
 'exit': [['close', '<', 'sma_short']]}

In [11]:
from MyTT import MA, BOLL

# closeData = data["close"].to_frame()
data["MA4"] = MA(data["close"], 4)
data["MA8"] = MA(data["close"], 8)

UPPER, MID, LOWER = BOLL(data["close"], 4)
data["BOLL4_U"] = UPPER
data["BOLL4_L"] = LOWER

UPPER, MID, LOWER = BOLL(data["close"], 8)
data["BOLL8_U"] = UPPER
data["BOLL8_L"] = LOWER

data.dropna(inplace=True)
data

,time,open,high,low,close,volume,date,MA4,MA8,BOLL4_U,BOLL4_L,BOLL8_U,BOLL8_L
7,1.701047e+09,3939.0,3948.0,3932.0,3947.0,44559,2023-11-27 09:05:00+08:00,3939.50,3937.250,3948.934,3930.066,3945.721,3928.779
8,1.701047e+09,3947.0,3957.0,3945.0,3952.0,52996,2023-11-27 09:10:00+08:00,3944.00,3939.500,3955.576,3932.424,3951.950,3927.050
9,1.701048e+09,3952.0,3957.0,3947.0,3951.0,30867,2023-11-27 09:15:00+08:00,3947.25,3941.125,3957.485,3937.015,3955.597,3926.653
10,1.701048e+09,3951.0,3951.0,3936.0,3944.0,40730,2023-11-27 09:20:00+08:00,3948.50,3942.250,3954.903,3942.097,3956.025,3928.475
11,1.701048e+09,3943.0,3944.0,3937.0,3943.0,18113,2023-11-27 09:25:00+08:00,3947.50,3943.500,3955.562,3939.438,3955.374,3931.626
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1.701826e+09,3876.0,3877.0,3872.0,3876.0,6410,2023-12-06 09:30:00+08:00,3875.75,3876.375,3881.645,3869.855,3881.468,3871.282
496,1.701826e+09,3875.0,3887.0,3875.0,3883.0,19817,2023-12-06 09:35:00+08:00,3878.75,3876.875,3884.112,3873.388,3883.466,3870.284
497,1.701827e+09,3883.0,3888.0,3880.0,3887.0,12664,2023-12-06 09:40:00+08:00,3880.75,3878.000,3889.736,3871.764,3887.434,3868.566
498,1.701827e+09,3887.0,3894.0,3882.0,3893.0,16905,2023-12-06 09:45:00+08:00,3884.75,3880.000,3897.109,3872.391,3893.601,3866.399
499,1.701827e+09,3894.0,3896.0,3887.0,3890.0,12461,2023-12-06 09:50:00+08:00,3888.25,3882.000,3895.649,3880.851,3896.177,3867.823